// Generated by CoffeeScript 1.6.3
module.exports = function() {
  var _this = this;
  this.addSignalListener('SIGQUIT', this.close);
  this.addSignalListener('SIGINT', this.destroy);
  this.addSignalListener('SIGTERM', this.destroy);
  this.addSignalListener('SIGUSR2', this.restart);
  this.addSignalListener('SIGTTIN', this.increase);
  this.addSignalListener('SIGTTOU', this.decrease);
  this.addSignalListener('SIGHUP', function() {
    return console.log(_this.workers.length, _this.settings.size);
  });
  return this;
};
